AnimationPointers:
	table_width 2, AnimationPointers
      dw CyndaquilAnimation
      dw QuilavaAnimation
      dw TyphlosionAnimation
      dw RowletAnimation
      dw DartrixAnimation
      dw DecidueyeAnimation
      dw OshawottAnimation
      dw DewottAnimation
      dw SamurottAnimation
      dw PidgeyAnimation
      dw PidgeottoAnimation
      dw PidgeotAnimation
      dw HoothootAnimation
      dw NoctowlAnimation
      dw SentretAnimation
      dw FurretAnimation
      dw PikachuAnimation
      dw RaichuAnimation
      dw LedybaAnimation
      dw LedianAnimation
      dw SpinarakAnimation
      dw AriadosAnimation
      dw GeodudeAnimation
      dw GravelerAnimation
      dw GolemAnimation
      dw ZubatAnimation
      dw GolbatAnimation
      dw CrobatAnimation
      dw ClefairyAnimation
      dw ClefableAnimation
      dw TogeticAnimation
      dw TogekissAnimation
      dw DunsparceAnimation
      dw DudunsparceAnimation
      dw MareepAnimation
      dw FlaaffyAnimation
      dw AmpharosAnimation
      dw WooperAnimation
      dw QuagsireAnimation
      dw GastlyAnimation
      dw HaunterAnimation
      dw GengarAnimation
      dw UnownAnimation
      dw OnixAnimation
      dw SteelixAnimation
      dw BellsproutAnimation
      dw WeepinbellAnimation
      dw VictreebelAnimation
      dw SkiploomAnimation
      dw JumpluffAnimation
      dw ParasAnimation
      dw ParasectAnimation
      dw PoliwagAnimation
      dw PoliwhirlAnimation
      dw PoliwrathAnimation
      dw PolitoedAnimation
      dw MagikarpAnimation
      dw GyaradosAnimation
      dw SlowpokeAnimation
      dw SlowbroAnimation
      dw SlowkingAnimation
      dw OddishAnimation
      dw GloomAnimation
      dw VileplumeAnimation
      dw BellossomAnimation
      dw AbraAnimation
      dw KadabraAnimation
      dw AlakazamAnimation
      dw PinecoAnimation
      dw ForretressAnimation
      dw NidoranAnimation
      dw NidorinaAnimation
      dw NidoqueenAnimation
      dw NidorinoAnimation
      dw NidokingAnimation
      dw YanmaAnimation
      dw YanmegaAnimation
      dw SunfloraAnimation
      dw ExeggcuteAnimation
      dw ExeggutorAnimation
      dw SudowoodoAnimation
      dw ScytherAnimation
      dw ScizorAnimation
      dw KleavorAnimation
      dw PinsirAnimation
      dw MinsirAnimation
      dw HeracrossAnimation
      dw KoffingAnimation
      dw WeezingAnimation
      dw GrimerAnimation
      dw MukAnimation
      dw MagnemiteAnimation
      dw MagnetonAnimation
      dw MagnezoneAnimation
      dw VoltorbAnimation
      dw ElectrodeAnimation
      dw AipomAnimation
      dw AmbipomAnimation
      dw SnubbullAnimation
      dw GranbullAnimation
      dw VulpixAnimation
      dw NinetalesAnimation
      dw GrowlitheAnimation
      dw ArcanineAnimation
      dw StantlerAnimation
      dw WyrdeerAnimation
      dw MarillAnimation
      dw AzumarillAnimation
      dw MankeyAnimation
      dw PrimeapeAnimation
      dw AnnihilapeAnimation
      dw MachopAnimation
      dw MachokeAnimation
      dw MachampAnimation
      dw HitmonleeAnimation
      dw HitmonchanAnimation
      dw HitmontopAnimation
      dw GirafarigAnimation
      dw FarigirafAnimation
      dw TaurosAnimation
      dw MiltankAnimation
      dw MagmarAnimation
      dw MagmortarAnimation
      dw JynxAnimation
      dw ElectabuzzAnimation
      dw ElectivireAnimation
      dw NatuAnimation
      dw XatuAnimation
      dw QwilfishAnimation
      dw OverqwilAnimation
      dw TentacoolAnimation
      dw TentacruelAnimation
      dw ShuckleAnimation
      dw CorsolaAnimation
      dw RemoraidAnimation
      dw OctilleryAnimation
      dw ChinchouAnimation
      dw LanturnAnimation
      dw TangelaAnimation
      dw TangrowthAnimation
      dw EeveeAnimation
      dw VaporeonAnimation
      dw JolteonAnimation
      dw FlareonAnimation
      dw EspeonAnimation
      dw UmbreonAnimation
      dw LeafeonAnimation
      dw GlaceonAnimation
      dw SylveonAnimation
      dw SeadraAnimation
      dw KingdraAnimation
      dw GligarAnimation
      dw GliscorAnimation
      dw SwinubAnimation
      dw PiloswineAnimation
      dw MamoswineAnimation
      dw TeddiursaAnimation
      dw UrsaringAnimation
      dw UrsalunaAnimation
      dw PhanpyAnimation
      dw DonphanAnimation
      dw MantineAnimation
      dw SkarmoryAnimation
      dw PonytaAnimation
      dw RapidashAnimation
      dw RhyhornAnimation
      dw RhydonAnimation
      dw RhyperiorAnimation
      dw MurkrowAnimation
      dw HonchkrowAnimation
      dw HoundourAnimation
      dw HoundoomAnimation
      dw SlugmaAnimation
      dw MagcargoAnimation
      dw SneaselAnimation
      dw WeavileAnimation
      dw SneaslerAnimation
      dw MisdreavusAnimation
      dw MismagiusAnimation
      dw PorygonAnimation
      dw Porygon2Animation
      dw Porygon_zAnimation
      dw ChanseyAnimation
      dw BlisseyAnimation
      dw LaprasAnimation
      dw SnorlaxAnimation
      dw ChikoritaAnimation
      dw BayleefAnimation
      dw MeganiumAnimation
      dw TotodileAnimation
      dw CroconawAnimation
      dw FeraligatrAnimation
      dw GrotleAnimation
      dw TorterraAnimation
      dw MonfernoAnimation
      dw InfernapeAnimation
      dw PrinplupAnimation
      dw EmpoleonAnimation
      dw StaraviaAnimation
      dw StaraptorAnimation
      dw ShinxAnimation
      dw LuxioAnimation
      dw LuxrayAnimation
      dw CranidosAnimation
      dw RampardosAnimation
      dw ShieldonAnimation
      dw BastiodonAnimation
      dw VespiquenAnimation
      dw DrifloonAnimation
      dw DrifblimAnimation
      dw BronzorAnimation
      dw BronzongAnimation
      dw SpiritombAnimation
      dw LucarioAnimation
      dw HippopotasAnimation
      dw HippowdonAnimation
      dw CroagunkAnimation
      dw ToxicroakAnimation
      dw SnoverAnimation
      dw AbomasnowAnimation
      dw DuskullAnimation
      dw DusclopsAnimation
      dw DusknoirAnimation
      dw FroslassAnimation
      dw RotomAnimation
      dw BergmiteAnimation
      dw AvaluggAnimation
      dw BasculegionAnimation
      dw BraviaryAnimation
      dw RaltsAnimation
      dw KirliaAnimation
      dw GardevoirAnimation
      dw GalladeAnimation
      dw GoomyAnimation
      dw SliggooAnimation
      dw GoodraAnimation
      dw ZoruaAnimation
      dw ZoroarkAnimation
      dw GibleAnimation
      dw GabiteAnimation
      dw GarchompAnimation
      dw DratiniAnimation
      dw DragonairAnimation
      dw DragoniteAnimation
      dw LarvitarAnimation
      dw PupitarAnimation
      dw TyranitarAnimation
      dw RaikouAnimation
      dw EnteiAnimation
      dw SuicuneAnimation
      dw HeatranAnimation
      dw LugiaAnimation
      dw Ho_ohAnimation
      dw CelebiAnimation
	assert_table_length NUM_POKEMON

	dw EggAnimation

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw Raichu_alolanAnimation
	dw Vulpix_alolanAnimation
	dw Ninetales_alolanAnimation
	dw Geodude_alolanAnimation
	dw Graveler_alolanAnimation
	dw Golem_alolanAnimation
	dw Grimer_alolanAnimation
	dw Muk_alolanAnimation
	dw Exeggutor_alolanAnimation


	dw Ponyta_galarianAnimation
	dw Rapidash_galarianAnimation
	dw Slowpoke_galarianAnimation
	dw Slowbro_galarianAnimation
	dw Slowking_galarianAnimation
	dw Weezing_galarianAnimation
	dw Corsola_galarianAnimation


	dw Growlithe_hisuianAnimation
	dw Arcanine_hisuianAnimation
	dw Voltorb_hisuianAnimation
	dw Electrode_hisuianAnimation
	dw Typhlosion_hisuianAnimation
	dw Qwilfish_hisuianAnimation
	dw Sneasel_hisuianAnimation
	dw Samurott_hisuianAnimation
	dw Decidueye_hisuianAnimation


	dw Noctowl_immortalAnimation
	dw Ursaluna_bloodmoonAnimation


	assert_table_length NUM_UNIQUE_POKEMON
