BitmasksPointers:
	table_width 2, BitmasksPointers
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw RowletBitmasks
	dw DartrixBitmasks
	dw DecidueyeBitmasks
	dw OshawottBitmasks
	dw DewottBitmasks
	dw SamurottBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw DunsparceBitmasks
	dw DudunsparceBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw UnownBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PolitoedBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw BellossomBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw NidoranBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw SunfloraBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw SudowoodoBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw KleavorBitmasks
	dw PinsirBitmasks
	dw MinsirBitmasks
	dw HeracrossBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw AipomBitmasks
	dw AmbipomBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw HitmontopBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw TaurosBitmasks
	dw MiltankBitmasks
	dw MagmarBitmasks
	dw MagmortarBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw ElectivireBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw QwilfishBitmasks
	dw OverqwilBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw ShuckleBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw UrsalunaBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw SneaslerBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw Porygon_zBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw LaprasBitmasks
	dw SnorlaxBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw GrotleBitmasks
	dw TorterraBitmasks
	dw MonfernoBitmasks
	dw InfernapeBitmasks
	dw PrinplupBitmasks
	dw EmpoleonBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw CranidosBitmasks
	dw RampardosBitmasks
	dw ShieldonBitmasks
	dw BastiodonBitmasks
	dw VespiquenBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw SpiritombBitmasks
	dw LucarioBitmasks
	dw HippopotasBitmasks
	dw HippowdonBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw FroslassBitmasks
	dw RotomBitmasks
	dw BergmiteBitmasks
	dw AvaluggBitmasks
	dw BasculegionBitmasks
	dw BraviaryBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw GoomyBitmasks
	dw SliggooBitmasks
	dw GoodraBitmasks
	dw ZoruaBitmasks
	dw ZoroarkBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw HeatranBitmasks
	dw LugiaBitmasks
	dw Ho_ohBitmasks
	dw CelebiBitmasks
	assert_table_length NUM_POKEMON

	dw EggBitmasks

	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	dw UnownExclamationBitmasks
	dw UnownQuestionBitmasks


	dw Raichu_alolanBitmasks
	dw Vulpix_alolanBitmasks
	dw Ninetales_alolanBitmasks
	dw Geodude_alolanBitmasks
	dw Graveler_alolanBitmasks
	dw Golem_alolanBitmasks
	dw Grimer_alolanBitmasks
	dw Muk_alolanBitmasks
	dw Exeggutor_alolanBitmasks


	dw Ponyta_galarianBitmasks
	dw Rapidash_galarianBitmasks
	dw Slowpoke_galarianBitmasks
	dw Slowbro_galarianBitmasks
	dw Slowking_galarianBitmasks
	dw Weezing_galarianBitmasks
	dw Corsola_galarianBitmasks


	dw Growlithe_hisuianBitmasks
	dw Arcanine_hisuianBitmasks
	dw Voltorb_hisuianBitmasks
	dw Electrode_hisuianBitmasks
	dw Typhlosion_hisuianBitmasks
	dw Qwilfish_hisuianBitmasks
	dw Sneasel_hisuianBitmasks
	dw Samurott_hisuianBitmasks
	dw Decidueye_hisuianBitmasks


	dw Noctowl_immortalBitmasks
	dw Ursaluna_bloodmoonBitmasks


	assert_table_length NUM_UNIQUE_POKEMON
