CyndaquilBitmasks:  INCLUDE "gfx/pokemon/cyndaquil/bitmask.asm"
QuilavaBitmasks:  INCLUDE "gfx/pokemon/quilava/bitmask.asm"

RowletBitmasks:  INCLUDE "gfx/pokemon/rowlet/bitmask.asm"
DartrixBitmasks:  INCLUDE "gfx/pokemon/dartrix/bitmask.asm"
OshawottBitmasks:  INCLUDE "gfx/pokemon/oshawott/bitmask.asm"
DewottBitmasks:  INCLUDE "gfx/pokemon/dewott/bitmask.asm"

HoothootBitmasks:  INCLUDE "gfx/pokemon/hoothoot/bitmask.asm"
SentretBitmasks:  INCLUDE "gfx/pokemon/sentret/bitmask.asm"
FurretBitmasks:  INCLUDE "gfx/pokemon/furret/bitmask.asm"
PikachuBitmasks:  INCLUDE "gfx/pokemon/pikachu/bitmask.asm"
LedybaBitmasks:  INCLUDE "gfx/pokemon/ledyba/bitmask.asm"

SpinarakBitmasks:  INCLUDE "gfx/pokemon/spinarak/bitmask.asm"
AriadosBitmasks:  INCLUDE "gfx/pokemon/ariados/bitmask.asm"

ZubatBitmasks:  INCLUDE "gfx/pokemon/zubat/bitmask.asm"
GolbatBitmasks:  INCLUDE "gfx/pokemon/golbat/bitmask.asm"
CrobatBitmasks:  INCLUDE "gfx/pokemon/crobat/bitmask.asm"
ClefairyBitmasks:  INCLUDE "gfx/pokemon/clefairy/bitmask.asm"
ClefableBitmasks:  INCLUDE "gfx/pokemon/clefable/bitmask.asm"
TogeticBitmasks:  INCLUDE "gfx/pokemon/togetic/bitmask.asm"
TogekissBitmasks:  INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
DunsparceBitmasks:  INCLUDE "gfx/pokemon/dunsparce/bitmask.asm"
DudunsparceBitmasks:  INCLUDE "gfx/pokemon/dudunsparce/bitmask.asm"
MareepBitmasks:  INCLUDE "gfx/pokemon/mareep/bitmask.asm"
FlaaffyBitmasks:  INCLUDE "gfx/pokemon/flaaffy/bitmask.asm"
AmpharosBitmasks:  INCLUDE "gfx/pokemon/ampharos/bitmask.asm"
WooperBitmasks:  INCLUDE "gfx/pokemon/wooper/bitmask.asm"
QuagsireBitmasks:  INCLUDE "gfx/pokemon/quagsire/bitmask.asm"
GastlyBitmasks:  INCLUDE "gfx/pokemon/gastly/bitmask.asm"
HaunterBitmasks:  INCLUDE "gfx/pokemon/haunter/bitmask.asm"
GengarBitmasks:  INCLUDE "gfx/pokemon/gengar/bitmask.asm"
UnownBitmasks:  INCLUDE "gfx/pokemon/unown/bitmask.asm"
OnixBitmasks:  INCLUDE "gfx/pokemon/onix/bitmask.asm"
SteelixBitmasks:  INCLUDE "gfx/pokemon/steelix/bitmask.asm"
BellsproutBitmasks:  INCLUDE "gfx/pokemon/bellsprout/bitmask.asm"
WeepinbellBitmasks:  INCLUDE "gfx/pokemon/weepinbell/bitmask.asm"
VictreebelBitmasks:  INCLUDE "gfx/pokemon/victreebel/bitmask.asm"
HoppipBitmasks:  INCLUDE "gfx/pokemon/hoppip/bitmask.asm"
SkiploomBitmasks:  INCLUDE "gfx/pokemon/skiploom/bitmask.asm"
JumpluffBitmasks:  INCLUDE "gfx/pokemon/jumpluff/bitmask.asm"
ParasBitmasks:  INCLUDE "gfx/pokemon/paras/bitmask.asm"
ParasectBitmasks:  INCLUDE "gfx/pokemon/parasect/bitmask.asm"
PoliwagBitmasks:  INCLUDE "gfx/pokemon/poliwag/bitmask.asm"
PoliwhirlBitmasks:  INCLUDE "gfx/pokemon/poliwhirl/bitmask.asm"
PoliwrathBitmasks:  INCLUDE "gfx/pokemon/poliwrath/bitmask.asm"
PolitoedBitmasks:  INCLUDE "gfx/pokemon/politoed/bitmask.asm"
MagikarpBitmasks:  INCLUDE "gfx/pokemon/magikarp/bitmask.asm"
GyaradosBitmasks:  INCLUDE "gfx/pokemon/gyarados/bitmask.asm"

OddishBitmasks:  INCLUDE "gfx/pokemon/oddish/bitmask.asm"
GloomBitmasks:  INCLUDE "gfx/pokemon/gloom/bitmask.asm"
VileplumeBitmasks:  INCLUDE "gfx/pokemon/vileplume/bitmask.asm"
BellossomBitmasks:  INCLUDE "gfx/pokemon/bellossom/bitmask.asm"
AbraBitmasks:  INCLUDE "gfx/pokemon/abra/bitmask.asm"
KadabraBitmasks:  INCLUDE "gfx/pokemon/kadabra/bitmask.asm"

DittoBitmasks:  INCLUDE "gfx/pokemon/ditto/bitmask.asm"
PinecoBitmasks:  INCLUDE "gfx/pokemon/pineco/bitmask.asm"
ForretressBitmasks:  INCLUDE "gfx/pokemon/forretress/bitmask.asm"
NidoranBitmasks:  INCLUDE "gfx/pokemon/nidoran/bitmask.asm"
NidorinaBitmasks:  INCLUDE "gfx/pokemon/nidorina/bitmask.asm"
NidoqueenBitmasks:  INCLUDE "gfx/pokemon/nidoqueen/bitmask.asm"
NidorinoBitmasks:  INCLUDE "gfx/pokemon/nidorino/bitmask.asm"
NidokingBitmasks:  INCLUDE "gfx/pokemon/nidoking/bitmask.asm"
YanmaBitmasks:  INCLUDE "gfx/pokemon/yanma/bitmask.asm"
YanmegaBitmasks:  INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
SunkernBitmasks:  INCLUDE "gfx/pokemon/sunkern/bitmask.asm"
SunfloraBitmasks:  INCLUDE "gfx/pokemon/sunflora/bitmask.asm"
ExeggcuteBitmasks:  INCLUDE "gfx/pokemon/exeggcute/bitmask.asm"

SudowoodoBitmasks:  INCLUDE "gfx/pokemon/sudowoodo/bitmask.asm"
ScytherBitmasks:  INCLUDE "gfx/pokemon/scyther/bitmask.asm"
ScizorBitmasks:  INCLUDE "gfx/pokemon/scizor/bitmask.asm"
KleavorBitmasks:  INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
PinsirBitmasks:  INCLUDE "gfx/pokemon/pinsir/bitmask.asm"
MinsirBitmasks:  INCLUDE "gfx/pokemon/minsir/bitmask.asm"
HeracrossBitmasks:  INCLUDE "gfx/pokemon/heracross/bitmask.asm"
KoffingBitmasks:  INCLUDE "gfx/pokemon/koffing/bitmask.asm"


MagnemiteBitmasks:  INCLUDE "gfx/pokemon/magnemite/bitmask.asm"
MagnetonBitmasks:  INCLUDE "gfx/pokemon/magneton/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"

AipomBitmasks:  INCLUDE "gfx/pokemon/aipom/bitmask.asm"
AmbipomBitmasks:  INCLUDE "gfx/pokemon/ambipom/bitmask.asm"
SnubbullBitmasks:  INCLUDE "gfx/pokemon/snubbull/bitmask.asm"
GranbullBitmasks:  INCLUDE "gfx/pokemon/granbull/bitmask.asm"


StantlerBitmasks:  INCLUDE "gfx/pokemon/stantler/bitmask.asm"
WyrdeerBitmasks:  INCLUDE "gfx/pokemon/wyrdeer/bitmask.asm"
MarillBitmasks:  INCLUDE "gfx/pokemon/marill/bitmask.asm"
AzumarillBitmasks:  INCLUDE "gfx/pokemon/azumarill/bitmask.asm"
MankeyBitmasks:  INCLUDE "gfx/pokemon/mankey/bitmask.asm"
PrimeapeBitmasks:  INCLUDE "gfx/pokemon/primeape/bitmask.asm"
AnnihilapeBitmasks:  INCLUDE "gfx/pokemon/annihilape/bitmask.asm"
MachopBitmasks:  INCLUDE "gfx/pokemon/machop/bitmask.asm"
MachokeBitmasks:  INCLUDE "gfx/pokemon/machoke/bitmask.asm"
MachampBitmasks:  INCLUDE "gfx/pokemon/machamp/bitmask.asm"
HitmonleeBitmasks:  INCLUDE "gfx/pokemon/hitmonlee/bitmask.asm"
HitmonchanBitmasks:  INCLUDE "gfx/pokemon/hitmonchan/bitmask.asm"
HitmontopBitmasks:  INCLUDE "gfx/pokemon/hitmontop/bitmask.asm"
GirafarigBitmasks:  INCLUDE "gfx/pokemon/girafarig/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/pokemon/farigiraf/bitmask.asm"
TaurosBitmasks:  INCLUDE "gfx/pokemon/tauros/bitmask.asm"
MiltankBitmasks:  INCLUDE "gfx/pokemon/miltank/bitmask.asm"
MagmarBitmasks:  INCLUDE "gfx/pokemon/magmar/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
JynxBitmasks:  INCLUDE "gfx/pokemon/jynx/bitmask.asm"
ElectabuzzBitmasks:  INCLUDE "gfx/pokemon/electabuzz/bitmask.asm"
ElectivireBitmasks:  INCLUDE "gfx/pokemon/electivire/bitmask.asm"
NatuBitmasks:  INCLUDE "gfx/pokemon/natu/bitmask.asm"


OverqwilBitmasks:  INCLUDE "gfx/pokemon/overqwil/bitmask.asm"
TentacoolBitmasks:  INCLUDE "gfx/pokemon/tentacool/bitmask.asm"
TentacruelBitmasks:  INCLUDE "gfx/pokemon/tentacruel/bitmask.asm"
ShuckleBitmasks:  INCLUDE "gfx/pokemon/shuckle/bitmask.asm"

RemoraidBitmasks:  INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
ChinchouBitmasks:  INCLUDE "gfx/pokemon/chinchou/bitmask.asm"
LanturnBitmasks:  INCLUDE "gfx/pokemon/lanturn/bitmask.asm"
TangelaBitmasks:  INCLUDE "gfx/pokemon/tangela/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
EeveeBitmasks:  INCLUDE "gfx/pokemon/eevee/bitmask.asm"
VaporeonBitmasks:  INCLUDE "gfx/pokemon/vaporeon/bitmask.asm"
JolteonBitmasks:  INCLUDE "gfx/pokemon/jolteon/bitmask.asm"
FlareonBitmasks:  INCLUDE "gfx/pokemon/flareon/bitmask.asm"
EspeonBitmasks:  INCLUDE "gfx/pokemon/espeon/bitmask.asm"
UmbreonBitmasks:  INCLUDE "gfx/pokemon/umbreon/bitmask.asm"
LeafeonBitmasks:  INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:  INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
SylveonBitmasks:  INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
HorseaBitmasks:  INCLUDE "gfx/pokemon/horsea/bitmask.asm"
SeadraBitmasks:  INCLUDE "gfx/pokemon/seadra/bitmask.asm"
KingdraBitmasks:  INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
GligarBitmasks:  INCLUDE "gfx/pokemon/gligar/bitmask.asm"
GliscorBitmasks:  INCLUDE "gfx/pokemon/gliscor/bitmask.asm"
SwinubBitmasks:  INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
TeddiursaBitmasks:  INCLUDE "gfx/pokemon/teddiursa/bitmask.asm"
UrsaringBitmasks:  INCLUDE "gfx/pokemon/ursaring/bitmask.asm"

PhanpyBitmasks:  INCLUDE "gfx/pokemon/phanpy/bitmask.asm"
DonphanBitmasks:  INCLUDE "gfx/pokemon/donphan/bitmask.asm"
MantineBitmasks:  INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:  INCLUDE "gfx/pokemon/skarmory/bitmask.asm"

RhyhornBitmasks:  INCLUDE "gfx/pokemon/rhyhorn/bitmask.asm"
RhydonBitmasks:  INCLUDE "gfx/pokemon/rhydon/bitmask.asm"
RhyperiorBitmasks:  INCLUDE "gfx/pokemon/rhyperior/bitmask.asm"
MurkrowBitmasks:  INCLUDE "gfx/pokemon/murkrow/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
HoundourBitmasks:  INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:  INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
SlugmaBitmasks:  INCLUDE "gfx/pokemon/slugma/bitmask.asm"

WeavileBitmasks:  INCLUDE "gfx/pokemon/weavile/bitmask.asm"
SneaslerBitmasks:  INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
MisdreavusBitmasks:  INCLUDE "gfx/pokemon/misdreavus/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
PorygonBitmasks:  INCLUDE "gfx/pokemon/porygon/bitmask.asm"
Porygon2Bitmasks:  INCLUDE "gfx/pokemon/porygon2/bitmask.asm"
Porygon_ZBitmasks:  INCLUDE "gfx/pokemon/porygon_z/bitmask.asm"
ChanseyBitmasks:  INCLUDE "gfx/pokemon/chansey/bitmask.asm"
BlisseyBitmasks:  INCLUDE "gfx/pokemon/blissey/bitmask.asm"
LaprasBitmasks:  INCLUDE "gfx/pokemon/lapras/bitmask.asm"
SnorlaxBitmasks:  INCLUDE "gfx/pokemon/snorlax/bitmask.asm"
ChikoritaBitmasks:  INCLUDE "gfx/pokemon/chikorita/bitmask.asm"
BayleefBitmasks:  INCLUDE "gfx/pokemon/bayleef/bitmask.asm"

TotodileBitmasks:  INCLUDE "gfx/pokemon/totodile/bitmask.asm"
CroconawBitmasks:  INCLUDE "gfx/pokemon/croconaw/bitmask.asm"

StarlyBitmasks:  INCLUDE "gfx/pokemon/starly/bitmask.asm"
StaraviaBitmasks:  INCLUDE "gfx/pokemon/staravia/bitmask.asm"
StaraptorBitmasks:  INCLUDE "gfx/pokemon/staraptor/bitmask.asm"
ShinxBitmasks:  INCLUDE "gfx/pokemon/shinx/bitmask.asm"
LuxioBitmasks:  INCLUDE "gfx/pokemon/luxio/bitmask.asm"
LuxrayBitmasks:  INCLUDE "gfx/pokemon/luxray/bitmask.asm"
CranidosBitmasks:  INCLUDE "gfx/pokemon/cranidos/bitmask.asm"
RampardosBitmasks:  INCLUDE "gfx/pokemon/rampardos/bitmask.asm"
ShieldonBitmasks:  INCLUDE "gfx/pokemon/shieldon/bitmask.asm"
BastiodonBitmasks:  INCLUDE "gfx/pokemon/bastiodon/bitmask.asm"
DrifloonBitmasks:  INCLUDE "gfx/pokemon/drifloon/bitmask.asm"
DrifblimBitmasks:  INCLUDE "gfx/pokemon/drifblim/bitmask.asm"
BronzorBitmasks:  INCLUDE "gfx/pokemon/bronzor/bitmask.asm"
BronzongBitmasks:  INCLUDE "gfx/pokemon/bronzong/bitmask.asm"
SpiritombBitmasks:  INCLUDE "gfx/pokemon/spiritomb/bitmask.asm"
RioluBitmasks:  INCLUDE "gfx/pokemon/riolu/bitmask.asm"
LucarioBitmasks:  INCLUDE "gfx/pokemon/lucario/bitmask.asm"
HippopotasBitmasks:  INCLUDE "gfx/pokemon/hippopotas/bitmask.asm"
HippowdonBitmasks:  INCLUDE "gfx/pokemon/hippowdon/bitmask.asm"
CroagunkBitmasks:  INCLUDE "gfx/pokemon/croagunk/bitmask.asm"
ToxicroakBitmasks:  INCLUDE "gfx/pokemon/toxicroak/bitmask.asm"
SnoverBitmasks:  INCLUDE "gfx/pokemon/snover/bitmask.asm"
AbomasnowBitmasks:  INCLUDE "gfx/pokemon/abomasnow/bitmask.asm"
DuskullBitmasks:  INCLUDE "gfx/pokemon/duskull/bitmask.asm"
DusclopsBitmasks:  INCLUDE "gfx/pokemon/dusclops/bitmask.asm"
DusknoirBitmasks:  INCLUDE "gfx/pokemon/dusknoir/bitmask.asm"
SnoruntBitmasks:  INCLUDE "gfx/pokemon/snorunt/bitmask.asm"
GlalieBitmasks:  INCLUDE "gfx/pokemon/glalie/bitmask.asm"
FroslassBitmasks:  INCLUDE "gfx/pokemon/froslass/bitmask.asm"
RotomBitmasks:  INCLUDE "gfx/pokemon/rotom/bitmask.asm"
BergmiteBitmasks:  INCLUDE "gfx/pokemon/bergmite/bitmask.asm"
AvaluggBitmasks:  INCLUDE "gfx/pokemon/avalugg/bitmask.asm"
BasculinBitmasks:  INCLUDE "gfx/pokemon/basculin/bitmask.asm"
BasculegionBitmasks:  INCLUDE "gfx/pokemon/basculegion/bitmask.asm"
RuffletBitmasks:  INCLUDE "gfx/pokemon/rufflet/bitmask.asm"
BraviaryBitmasks:  INCLUDE "gfx/pokemon/braviary/bitmask.asm"
RaltsBitmasks:  INCLUDE "gfx/pokemon/ralts/bitmask.asm"
KirliaBitmasks:  INCLUDE "gfx/pokemon/kirlia/bitmask.asm"
GardevoirBitmasks:  INCLUDE "gfx/pokemon/gardevoir/bitmask.asm"
GalladeBitmasks:  INCLUDE "gfx/pokemon/gallade/bitmask.asm"
GoomyBitmasks:  INCLUDE "gfx/pokemon/goomy/bitmask.asm"
SliggooBitmasks:  INCLUDE "gfx/pokemon/sliggoo/bitmask.asm"
GoodraBitmasks:  INCLUDE "gfx/pokemon/goodra/bitmask.asm"
ZoruaBitmasks:  INCLUDE "gfx/pokemon/zorua/bitmask.asm"
ZoroarkBitmasks:  INCLUDE "gfx/pokemon/zoroark/bitmask.asm"
GibleBitmasks:  INCLUDE "gfx/pokemon/gible/bitmask.asm"
GabiteBitmasks:  INCLUDE "gfx/pokemon/gabite/bitmask.asm"
GarchompBitmasks:  INCLUDE "gfx/pokemon/garchomp/bitmask.asm"
DratiniBitmasks:  INCLUDE "gfx/pokemon/dratini/bitmask.asm"
DragonairBitmasks:  INCLUDE "gfx/pokemon/dragonair/bitmask.asm"
DragoniteBitmasks:  INCLUDE "gfx/pokemon/dragonite/bitmask.asm"
LarvitarBitmasks:  INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:  INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
RaikouBitmasks:  INCLUDE "gfx/pokemon/raikou/bitmask.asm"
EnteiBitmasks:  INCLUDE "gfx/pokemon/entei/bitmask.asm"
SuicuneBitmasks:  INCLUDE "gfx/pokemon/suicune/bitmask.asm"
HeatranBitmasks:  INCLUDE "gfx/pokemon/heatran/bitmask.asm"
LugiaBitmasks:  INCLUDE "gfx/pokemon/lugia/bitmask.asm"
Ho_OhBitmasks:  INCLUDE "gfx/pokemon/ho_oh/bitmask.asm"
CelebiBitmasks:  INCLUDE "gfx/pokemon/celebi/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.asm"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.asm"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.asm"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.asm"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.asm"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.asm"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.asm"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.asm"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.asm"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.asm"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.asm"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.asm"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.asm"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.asm"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.asm"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.asm"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.asm"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.asm"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.asm"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.asm"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.asm"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.asm"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.asm"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.asm"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.asm"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.asm"
UnownExclamationBitmasks: INCLUDE "gfx/pokemon/unown_exclamation/bitmask.asm"
UnownQuestionBitmasks:    INCLUDE "gfx/pokemon/unown_question/bitmask.asm"


RaichuBitmasks:  INCLUDE "gfx/pokemon/raichu/bitmask.asm"
Raichu_AlolanBitmasks:  INCLUDE "gfx/pokemon/raichu_alolan/bitmask.asm"

VulpixBitmasks:  INCLUDE "gfx/pokemon/vulpix/bitmask.asm"
Vulpix_AlolanBitmasks:  INCLUDE "gfx/pokemon/vulpix_alolan/bitmask.asm"

NinetalesBitmasks:  INCLUDE "gfx/pokemon/ninetales/bitmask.asm"
Ninetales_AlolanBitmasks:  INCLUDE "gfx/pokemon/ninetales_alolan/bitmask.asm"

GeodudeBitmasks:  INCLUDE "gfx/pokemon/geodude/bitmask.asm"
Geodude_AlolanBitmasks:  INCLUDE "gfx/pokemon/geodude_alolan/bitmask.asm"

GravelerBitmasks:  INCLUDE "gfx/pokemon/graveler/bitmask.asm"
Graveler_AlolanBitmasks:  INCLUDE "gfx/pokemon/graveler_alolan/bitmask.asm"

GolemBitmasks:  INCLUDE "gfx/pokemon/golem/bitmask.asm"
Golem_AlolanBitmasks:  INCLUDE "gfx/pokemon/golem_alolan/bitmask.asm"

GrimerBitmasks:  INCLUDE "gfx/pokemon/grimer/bitmask.asm"
Grimer_AlolanBitmasks:  INCLUDE "gfx/pokemon/grimer_alolan/bitmask.asm"

MukBitmasks:  INCLUDE "gfx/pokemon/muk/bitmask.asm"
Muk_AlolanBitmasks:  INCLUDE "gfx/pokemon/muk_alolan/bitmask.asm"

ExeggutorBitmasks:  INCLUDE "gfx/pokemon/exeggutor/bitmask.asm"
Exeggutor_AlolanBitmasks:  INCLUDE "gfx/pokemon/exeggutor_alolan/bitmask.asm"


PonytaBitmasks:  INCLUDE "gfx/pokemon/ponyta/bitmask.asm"
Ponyta_GalarianBitmasks:  INCLUDE "gfx/pokemon/ponyta_galarian/bitmask.asm"

RapidashBitmasks:  INCLUDE "gfx/pokemon/rapidash/bitmask.asm"
Rapidash_GalarianBitmasks:  INCLUDE "gfx/pokemon/rapidash_galarian/bitmask.asm"

SlowpokeBitmasks:  INCLUDE "gfx/pokemon/slowpoke/bitmask.asm"
Slowpoke_GalarianBitmasks:  INCLUDE "gfx/pokemon/slowpoke_galarian/bitmask.asm"

SlowbroBitmasks:  INCLUDE "gfx/pokemon/slowbro/bitmask.asm"
Slowbro_GalarianBitmasks:  INCLUDE "gfx/pokemon/slowbro_galarian/bitmask.asm"

SlowkingBitmasks:  INCLUDE "gfx/pokemon/slowking/bitmask.asm"
Slowking_GalarianBitmasks:  INCLUDE "gfx/pokemon/slowking_galarian/bitmask.asm"

WeezingBitmasks:  INCLUDE "gfx/pokemon/weezing/bitmask.asm"
Weezing_GalarianBitmasks:  INCLUDE "gfx/pokemon/weezing_galarian/bitmask.asm"

CorsolaBitmasks:  INCLUDE "gfx/pokemon/corsola/bitmask.asm"
Corsola_GalarianBitmasks:  INCLUDE "gfx/pokemon/corsola_galarian/bitmask.asm"


GrowlitheBitmasks:  INCLUDE "gfx/pokemon/growlithe/bitmask.asm"
Growlithe_HisuianBitmasks:  INCLUDE "gfx/pokemon/growlithe_hisuian/bitmask.asm"

ArcanineBitmasks:  INCLUDE "gfx/pokemon/arcanine/bitmask.asm"
Arcanine_HisuianBitmasks:  INCLUDE "gfx/pokemon/arcanine_hisuian/bitmask.asm"

VoltorbBitmasks:  INCLUDE "gfx/pokemon/voltorb/bitmask.asm"
Voltorb_HisuianBitmasks:  INCLUDE "gfx/pokemon/voltorb_hisuian/bitmask.asm"

ElectrodeBitmasks:  INCLUDE "gfx/pokemon/electrode/bitmask.asm"
Electrode_HisuianBitmasks:  INCLUDE "gfx/pokemon/electrode_hisuian/bitmask.asm"

TyphlosionBitmasks:  INCLUDE "gfx/pokemon/typhlosion/bitmask.asm"
Typhlosion_HisuianBitmasks:  INCLUDE "gfx/pokemon/typhlosion_hisuian/bitmask.asm"

QwilfishBitmasks:  INCLUDE "gfx/pokemon/qwilfish/bitmask.asm"
Qwilfish_HisuianBitmasks:  INCLUDE "gfx/pokemon/qwilfish_hisuian/bitmask.asm"

SneaselBitmasks:  INCLUDE "gfx/pokemon/sneasel/bitmask.asm"
Sneasel_HisuianBitmasks:  INCLUDE "gfx/pokemon/sneasel_hisuian/bitmask.asm"

SamurottBitmasks:  INCLUDE "gfx/pokemon/samurott/bitmask.asm"
Samurott_HisuianBitmasks:  INCLUDE "gfx/pokemon/samurott_hisuian/bitmask.asm"

DecidueyeBitmasks:  INCLUDE "gfx/pokemon/decidueye/bitmask.asm"
Decidueye_HisuianBitmasks:  INCLUDE "gfx/pokemon/decidueye_hisuian/bitmask.asm"

NoctowlBitmasks:  INCLUDE "gfx/pokemon/noctowl/bitmask.asm"
Noctowl_ImmortalBitmasks:  INCLUDE "gfx/pokemon/noctowl_immortal/bitmask.asm"

UrsalunaBitmasks:  INCLUDE "gfx/pokemon/ursaluna/bitmask.asm"
Ursaluna_BloodmoonBitmasks:  INCLUDE "gfx/pokemon/ursaluna_bloodmoon/bitmask.asm"

FeraligatrBitmasks:  INCLUDE "gfx/pokemon/feraligatr/bitmask.asm"
Feraligatr_AncestorBitmasks:  INCLUDE "gfx/pokemon/feraligatr_ancestor/bitmask.asm"

MeganiumBitmasks:  INCLUDE "gfx/pokemon/meganium/bitmask.asm"
Meganium_AncestorBitmasks:  INCLUDE "gfx/pokemon/meganium_ancestor/bitmask.asm"

MagcargoBitmasks:  INCLUDE "gfx/pokemon/magcargo/bitmask.asm"
Magcargo_AncestorBitmasks:  INCLUDE "gfx/pokemon/magcargo_ancestor/bitmask.asm"

XatuBitmasks:  INCLUDE "gfx/pokemon/xatu/bitmask.asm"
Xatu_AncestorBitmasks:  INCLUDE "gfx/pokemon/xatu_ancestor/bitmask.asm"

LedianBitmasks:  INCLUDE "gfx/pokemon/ledian/bitmask.asm"
Ledian_AncestorBitmasks:  INCLUDE "gfx/pokemon/ledian_ancestor/bitmask.asm"

AlakazamBitmasks:  INCLUDE "gfx/pokemon/alakazam/bitmask.asm"
Alakazam_AncestorBitmasks:  INCLUDE "gfx/pokemon/alakazam_ancestor/bitmask.asm"

