AnimationExtraPointers:
	table_width 2, AnimationExtraPointers
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw RowletAnimationExtra
	dw DartrixAnimationExtra
	dw DecidueyeAnimationExtra
	dw OshawottAnimationExtra
	dw DewottAnimationExtra
	dw SamurottAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw HoothootAnimationExtra
	dw NoctowlAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw PikachuAnimationExtra
	dw RaichuAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw SpinarakAnimationExtra
	dw AriadosAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw CrobatAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw TogeticAnimationExtra
	dw TogekissAnimationExtra
	dw DunsparceAnimationExtra
	dw DudunsparceAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw UnownAnimationExtra
	dw OnixAnimationExtra
	dw SteelixAnimationExtra
	dw BellsproutAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw SkiploomAnimationExtra
	dw JumpluffAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw PolitoedAnimationExtra
	dw MagikarpAnimationExtra
	dw GyaradosAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw SlowkingAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw BellossomAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw NidoranAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw SunfloraAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw SudowoodoAnimationExtra
	dw ScytherAnimationExtra
	dw ScizorAnimationExtra
	dw KleavorAnimationExtra
	dw PinsirAnimationExtra
	dw MinsirAnimationExtra
	dw HeracrossAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw GrimerAnimationExtra
	dw MukAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw MagnezoneAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw AipomAnimationExtra
	dw AmbipomAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw VulpixAnimationExtra
	dw NinetalesAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw StantlerAnimationExtra
	dw WyrdeerAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw AnnihilapeAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw HitmontopAnimationExtra
	dw GirafarigAnimationExtra
	dw FarigirafAnimationExtra
	dw TaurosAnimationExtra
	dw MiltankAnimationExtra
	dw MagmarAnimationExtra
	dw MagmortarAnimationExtra
	dw JynxAnimationExtra
	dw ElectabuzzAnimationExtra
	dw ElectivireAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw QwilfishAnimationExtra
	dw OverqwilAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw ShuckleAnimationExtra
	dw CorsolaAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw TangelaAnimationExtra
	dw TangrowthAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw SylveonAnimationExtra
	dw SeadraAnimationExtra
	dw KingdraAnimationExtra
	dw GligarAnimationExtra
	dw GliscorAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw MamoswineAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw UrsalunaAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw RhyperiorAnimationExtra
	dw MurkrowAnimationExtra
	dw HonchkrowAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SneaselAnimationExtra
	dw WeavileAnimationExtra
	dw SneaslerAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw PorygonAnimationExtra
	dw Porygon2AnimationExtra
	dw Porygon_zAnimationExtra
	dw ChanseyAnimationExtra
	dw BlisseyAnimationExtra
	dw LaprasAnimationExtra
	dw SnorlaxAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw GrotleAnimationExtra
	dw TorterraAnimationExtra
	dw MonfernoAnimationExtra
	dw InfernapeAnimationExtra
	dw PrinplupAnimationExtra
	dw EmpoleonAnimationExtra
	dw StaraviaAnimationExtra
	dw StaraptorAnimationExtra
	dw ShinxAnimationExtra
	dw LuxioAnimationExtra
	dw LuxrayAnimationExtra
	dw CranidosAnimationExtra
	dw RampardosAnimationExtra
	dw ShieldonAnimationExtra
	dw BastiodonAnimationExtra
	dw VespiquenAnimationExtra
	dw DrifloonAnimationExtra
	dw DrifblimAnimationExtra
	dw BronzorAnimationExtra
	dw BronzongAnimationExtra
	dw SpiritombAnimationExtra
	dw LucarioAnimationExtra
	dw HippopotasAnimationExtra
	dw HippowdonAnimationExtra
	dw CroagunkAnimationExtra
	dw ToxicroakAnimationExtra
	dw SnoverAnimationExtra
	dw AbomasnowAnimationExtra
	dw DuskullAnimationExtra
	dw DusclopsAnimationExtra
	dw DusknoirAnimationExtra
	dw FroslassAnimationExtra
	dw RotomAnimationExtra
	dw BergmiteAnimationExtra
	dw AvaluggAnimationExtra
	dw BasculegionAnimationExtra
	dw BraviaryAnimationExtra
	dw RaltsAnimationExtra
	dw KirliaAnimationExtra
	dw GardevoirAnimationExtra
	dw GalladeAnimationExtra
	dw GoomyAnimationExtra
	dw SliggooAnimationExtra
	dw GoodraAnimationExtra
	dw ZoruaAnimationExtra
	dw ZoroarkAnimationExtra
	dw GibleAnimationExtra
	dw GabiteAnimationExtra
	dw GarchompAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw HeatranAnimationExtra
	dw LugiaAnimationExtra
	dw Ho_ohAnimationExtra
	dw CelebiAnimationExtra

	assert_table_length NUM_POKEMON

	dw EggAnimationExtra

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw Raichu_alolanAnimationExtra
	dw Vulpix_alolanAnimationExtra
	dw Ninetales_alolanAnimationExtra
	dw Geodude_alolanAnimationExtra
	dw Graveler_alolanAnimationExtra
	dw Golem_alolanAnimationExtra
	dw Grimer_alolanAnimationExtra
	dw Muk_alolanAnimationExtra
	dw Exeggutor_alolanAnimationExtra


	dw Ponyta_galarianAnimationExtra
	dw Rapidash_galarianAnimationExtra
	dw Slowpoke_galarianAnimationExtra
	dw Slowbro_galarianAnimationExtra
	dw Slowking_galarianAnimationExtra
	dw Weezing_galarianAnimationExtra
	dw Corsola_galarianAnimationExtra


	dw Growlithe_hisuianAnimationExtra
	dw Arcanine_hisuianAnimationExtra
	dw Voltorb_hisuianAnimationExtra
	dw Electrode_hisuianAnimationExtra
	dw Typhlosion_hisuianAnimationExtra
	dw Qwilfish_hisuianAnimationExtra
	dw Sneasel_hisuianAnimationExtra
	dw Samurott_hisuianAnimationExtra
	dw Decidueye_hisuianAnimationExtra


	dw Noctowl_immortalAnimationExtra
	dw Ursaluna_bloodmoonAnimationExtra


	assert_table_length NUM_UNIQUE_POKEMON

