CyndaquilAnimationExtra:  INCLUDE "gfx/pokemon/cyndaquil/anim1.asm"
QuilavaAnimationExtra:  INCLUDE "gfx/pokemon/quilava/anim1.asm"
RowletAnimationExtra:  INCLUDE "gfx/pokemon/rowlet/anim1.asm"
DartrixAnimationExtra:  INCLUDE "gfx/pokemon/dartrix/anim1.asm"
OshawottAnimationExtra:  INCLUDE "gfx/pokemon/oshawott/anim1.asm"
DewottAnimationExtra:  INCLUDE "gfx/pokemon/dewott/anim1.asm"

HoothootAnimationExtra:  INCLUDE "gfx/pokemon/hoothoot/anim1.asm"
SentretAnimationExtra:  INCLUDE "gfx/pokemon/sentret/anim1.asm"
FurretAnimationExtra:  INCLUDE "gfx/pokemon/furret/anim1.asm"
PikachuAnimationExtra:  INCLUDE "gfx/pokemon/pikachu/anim1.asm"

LedybaAnimationExtra:  INCLUDE "gfx/pokemon/ledyba/anim1.asm"

SpinarakAnimationExtra:  INCLUDE "gfx/pokemon/spinarak/anim1.asm"
AriadosAnimationExtra:  INCLUDE "gfx/pokemon/ariados/anim1.asm"

ZubatAnimationExtra:  INCLUDE "gfx/pokemon/zubat/anim1.asm"
GolbatAnimationExtra:  INCLUDE "gfx/pokemon/golbat/anim1.asm"
CrobatAnimationExtra:  INCLUDE "gfx/pokemon/crobat/anim1.asm"
ClefairyAnimationExtra:  INCLUDE "gfx/pokemon/clefairy/anim1.asm"
ClefableAnimationExtra:  INCLUDE "gfx/pokemon/clefable/anim1.asm"
TogeticAnimationExtra:  INCLUDE "gfx/pokemon/togetic/anim1.asm"
TogekissAnimationExtra:  INCLUDE "gfx/pokemon/togekiss/anim1.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim1.asm"
DudunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dudunsparce/anim1.asm"
MareepAnimationExtra:  INCLUDE "gfx/pokemon/mareep/anim1.asm"
FlaaffyAnimationExtra:  INCLUDE "gfx/pokemon/flaaffy/anim1.asm"
AmpharosAnimationExtra:  INCLUDE "gfx/pokemon/ampharos/anim1.asm"
WooperAnimationExtra:  INCLUDE "gfx/pokemon/wooper/anim1.asm"
QuagsireAnimationExtra:  INCLUDE "gfx/pokemon/quagsire/anim1.asm"
GastlyAnimationExtra:  INCLUDE "gfx/pokemon/gastly/anim1.asm"
HaunterAnimationExtra:  INCLUDE "gfx/pokemon/haunter/anim1.asm"
GengarAnimationExtra:  INCLUDE "gfx/pokemon/gengar/anim1.asm"
UnownAnimationExtra:  INCLUDE "gfx/pokemon/unown/anim1.asm"
OnixAnimationExtra:  INCLUDE "gfx/pokemon/onix/anim1.asm"
SteelixAnimationExtra:  INCLUDE "gfx/pokemon/steelix/anim1.asm"
BellsproutAnimationExtra:  INCLUDE "gfx/pokemon/bellsprout/anim1.asm"
WeepinbellAnimationExtra:  INCLUDE "gfx/pokemon/weepinbell/anim1.asm"
VictreebelAnimationExtra:  INCLUDE "gfx/pokemon/victreebel/anim1.asm"
HoppipAnimationExtra:  INCLUDE "gfx/pokemon/hoppip/anim1.asm"
SkiploomAnimationExtra:  INCLUDE "gfx/pokemon/skiploom/anim1.asm"
JumpluffAnimationExtra:  INCLUDE "gfx/pokemon/jumpluff/anim1.asm"
ParasAnimationExtra:  INCLUDE "gfx/pokemon/paras/anim1.asm"
ParasectAnimationExtra:  INCLUDE "gfx/pokemon/parasect/anim1.asm"
PoliwagAnimationExtra:  INCLUDE "gfx/pokemon/poliwag/anim1.asm"
PoliwhirlAnimationExtra:  INCLUDE "gfx/pokemon/poliwhirl/anim1.asm"
PoliwrathAnimationExtra:  INCLUDE "gfx/pokemon/poliwrath/anim1.asm"
PolitoedAnimationExtra:  INCLUDE "gfx/pokemon/politoed/anim1.asm"
MagikarpAnimationExtra:  INCLUDE "gfx/pokemon/magikarp/anim1.asm"
GyaradosAnimationExtra:  INCLUDE "gfx/pokemon/gyarados/anim1.asm"

OddishAnimationExtra:  INCLUDE "gfx/pokemon/oddish/anim1.asm"
GloomAnimationExtra:  INCLUDE "gfx/pokemon/gloom/anim1.asm"
VileplumeAnimationExtra:  INCLUDE "gfx/pokemon/vileplume/anim1.asm"
BellossomAnimationExtra:  INCLUDE "gfx/pokemon/bellossom/anim1.asm"
AbraAnimationExtra:  INCLUDE "gfx/pokemon/abra/anim1.asm"
KadabraAnimationExtra:  INCLUDE "gfx/pokemon/kadabra/anim1.asm"
DittoAnimationExtra:  INCLUDE "gfx/pokemon/ditto/anim1.asm"
PinecoAnimationExtra:  INCLUDE "gfx/pokemon/pineco/anim1.asm"
ForretressAnimationExtra:  INCLUDE "gfx/pokemon/forretress/anim1.asm"
NidoranAnimationExtra:  INCLUDE "gfx/pokemon/nidoran/anim1.asm"
NidorinaAnimationExtra:  INCLUDE "gfx/pokemon/nidorina/anim1.asm"
NidoqueenAnimationExtra:  INCLUDE "gfx/pokemon/nidoqueen/anim1.asm"
NidorinoAnimationExtra:  INCLUDE "gfx/pokemon/nidorino/anim1.asm"
NidokingAnimationExtra:  INCLUDE "gfx/pokemon/nidoking/anim1.asm"
YanmaAnimationExtra:  INCLUDE "gfx/pokemon/yanma/anim1.asm"
YanmegaAnimationExtra:  INCLUDE "gfx/pokemon/yanmega/anim1.asm"
SunkernAnimationExtra:  INCLUDE "gfx/pokemon/sunkern/anim1.asm"
SunfloraAnimationExtra:  INCLUDE "gfx/pokemon/sunflora/anim1.asm"
ExeggcuteAnimationExtra:  INCLUDE "gfx/pokemon/exeggcute/anim1.asm"

SudowoodoAnimationExtra:  INCLUDE "gfx/pokemon/sudowoodo/anim1.asm"
ScytherAnimationExtra:  INCLUDE "gfx/pokemon/scyther/anim1.asm"
ScizorAnimationExtra:  INCLUDE "gfx/pokemon/scizor/anim1.asm"
KleavorAnimationExtra:  INCLUDE "gfx/pokemon/kleavor/anim1.asm"
PinsirAnimationExtra:  INCLUDE "gfx/pokemon/pinsir/anim1.asm"
MinsirAnimationExtra:  INCLUDE "gfx/pokemon/minsir/anim1.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim1.asm"
KoffingAnimationExtra:  INCLUDE "gfx/pokemon/koffing/anim1.asm"
MagnemiteAnimationExtra:  INCLUDE "gfx/pokemon/magnemite/anim1.asm"
MagnetonAnimationExtra:  INCLUDE "gfx/pokemon/magneton/anim1.asm"
MagnezoneAnimationExtra:  INCLUDE "gfx/pokemon/magnezone/anim1.asm"

AipomAnimationExtra:  INCLUDE "gfx/pokemon/aipom/anim1.asm"
AmbipomAnimationExtra:  INCLUDE "gfx/pokemon/ambipom/anim1.asm"
SnubbullAnimationExtra:  INCLUDE "gfx/pokemon/snubbull/anim1.asm"
GranbullAnimationExtra:  INCLUDE "gfx/pokemon/granbull/anim1.asm"


StantlerAnimationExtra:  INCLUDE "gfx/pokemon/stantler/anim1.asm"
WyrdeerAnimationExtra:  INCLUDE "gfx/pokemon/wyrdeer/anim1.asm"
MarillAnimationExtra:  INCLUDE "gfx/pokemon/marill/anim1.asm"
AzumarillAnimationExtra:  INCLUDE "gfx/pokemon/azumarill/anim1.asm"
MankeyAnimationExtra:  INCLUDE "gfx/pokemon/mankey/anim1.asm"
PrimeapeAnimationExtra:  INCLUDE "gfx/pokemon/primeape/anim1.asm"
AnnihilapeAnimationExtra:  INCLUDE "gfx/pokemon/annihilape/anim1.asm"
MachopAnimationExtra:  INCLUDE "gfx/pokemon/machop/anim1.asm"
MachokeAnimationExtra:  INCLUDE "gfx/pokemon/machoke/anim1.asm"
MachampAnimationExtra:  INCLUDE "gfx/pokemon/machamp/anim1.asm"
HitmonleeAnimationExtra:  INCLUDE "gfx/pokemon/hitmonlee/anim1.asm"
HitmonchanAnimationExtra:  INCLUDE "gfx/pokemon/hitmonchan/anim1.asm"
HitmontopAnimationExtra:  INCLUDE "gfx/pokemon/hitmontop/anim1.asm"
GirafarigAnimationExtra:  INCLUDE "gfx/pokemon/girafarig/anim1.asm"
FarigirafAnimationExtra:  INCLUDE "gfx/pokemon/farigiraf/anim1.asm"
TaurosAnimationExtra:  INCLUDE "gfx/pokemon/tauros/anim1.asm"
MiltankAnimationExtra:  INCLUDE "gfx/pokemon/miltank/anim1.asm"
MagmarAnimationExtra:  INCLUDE "gfx/pokemon/magmar/anim1.asm"
MagmortarAnimationExtra:  INCLUDE "gfx/pokemon/magmortar/anim1.asm"
JynxAnimationExtra:  INCLUDE "gfx/pokemon/jynx/anim1.asm"
ElectabuzzAnimationExtra:  INCLUDE "gfx/pokemon/electabuzz/anim1.asm"
ElectivireAnimationExtra:  INCLUDE "gfx/pokemon/electivire/anim1.asm"
NatuAnimationExtra:  INCLUDE "gfx/pokemon/natu/anim1.asm"

OverqwilAnimationExtra:  INCLUDE "gfx/pokemon/overqwil/anim1.asm"
TentacoolAnimationExtra:  INCLUDE "gfx/pokemon/tentacool/anim1.asm"
TentacruelAnimationExtra:  INCLUDE "gfx/pokemon/tentacruel/anim1.asm"
ShuckleAnimationExtra:  INCLUDE "gfx/pokemon/shuckle/anim1.asm"

RemoraidAnimationExtra:  INCLUDE "gfx/pokemon/remoraid/anim1.asm"
OctilleryAnimationExtra:  INCLUDE "gfx/pokemon/octillery/anim1.asm"
ChinchouAnimationExtra:  INCLUDE "gfx/pokemon/chinchou/anim1.asm"
LanturnAnimationExtra:  INCLUDE "gfx/pokemon/lanturn/anim1.asm"
TangelaAnimationExtra:  INCLUDE "gfx/pokemon/tangela/anim1.asm"
TangrowthAnimationExtra:  INCLUDE "gfx/pokemon/tangrowth/anim1.asm"
EeveeAnimationExtra:  INCLUDE "gfx/pokemon/eevee/anim1.asm"
VaporeonAnimationExtra:  INCLUDE "gfx/pokemon/vaporeon/anim1.asm"
JolteonAnimationExtra:  INCLUDE "gfx/pokemon/jolteon/anim1.asm"
FlareonAnimationExtra:  INCLUDE "gfx/pokemon/flareon/anim1.asm"
EspeonAnimationExtra:  INCLUDE "gfx/pokemon/espeon/anim1.asm"
UmbreonAnimationExtra:  INCLUDE "gfx/pokemon/umbreon/anim1.asm"
LeafeonAnimationExtra:  INCLUDE "gfx/pokemon/leafeon/anim1.asm"
GlaceonAnimationExtra:  INCLUDE "gfx/pokemon/glaceon/anim1.asm"
SylveonAnimationExtra:  INCLUDE "gfx/pokemon/sylveon/anim1.asm"
HorseaAnimationExtra:  INCLUDE "gfx/pokemon/horsea/anim1.asm"
SeadraAnimationExtra:  INCLUDE "gfx/pokemon/seadra/anim1.asm"
KingdraAnimationExtra:  INCLUDE "gfx/pokemon/kingdra/anim1.asm"
GligarAnimationExtra:  INCLUDE "gfx/pokemon/gligar/anim1.asm"
GliscorAnimationExtra:  INCLUDE "gfx/pokemon/gliscor/anim1.asm"
SwinubAnimationExtra:  INCLUDE "gfx/pokemon/swinub/anim1.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim1.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim1.asm"
TeddiursaAnimationExtra:  INCLUDE "gfx/pokemon/teddiursa/anim1.asm"
UrsaringAnimationExtra:  INCLUDE "gfx/pokemon/ursaring/anim1.asm"

PhanpyAnimationExtra:  INCLUDE "gfx/pokemon/phanpy/anim1.asm"
DonphanAnimationExtra:  INCLUDE "gfx/pokemon/donphan/anim1.asm"
MantineAnimationExtra:  INCLUDE "gfx/pokemon/mantine/anim1.asm"
SkarmoryAnimationExtra:  INCLUDE "gfx/pokemon/skarmory/anim1.asm"

RhyhornAnimationExtra:  INCLUDE "gfx/pokemon/rhyhorn/anim1.asm"
RhydonAnimationExtra:  INCLUDE "gfx/pokemon/rhydon/anim1.asm"
RhyperiorAnimationExtra:  INCLUDE "gfx/pokemon/rhyperior/anim1.asm"
MurkrowAnimationExtra:  INCLUDE "gfx/pokemon/murkrow/anim1.asm"
HonchkrowAnimationExtra:  INCLUDE "gfx/pokemon/honchkrow/anim1.asm"
HoundourAnimationExtra:  INCLUDE "gfx/pokemon/houndour/anim1.asm"
HoundoomAnimationExtra:  INCLUDE "gfx/pokemon/houndoom/anim1.asm"
SlugmaAnimationExtra:  INCLUDE "gfx/pokemon/slugma/anim1.asm"
WeavileAnimationExtra:  INCLUDE "gfx/pokemon/weavile/anim1.asm"
SneaslerAnimationExtra:  INCLUDE "gfx/pokemon/sneasler/anim1.asm"
MisdreavusAnimationExtra:  INCLUDE "gfx/pokemon/misdreavus/anim1.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim1.asm"
PorygonAnimationExtra:  INCLUDE "gfx/pokemon/porygon/anim1.asm"
Porygon2AnimationExtra:  INCLUDE "gfx/pokemon/porygon2/anim1.asm"
Porygon_ZAnimationExtra:  INCLUDE "gfx/pokemon/porygon_z/anim1.asm"
ChanseyAnimationExtra:  INCLUDE "gfx/pokemon/chansey/anim1.asm"
BlisseyAnimationExtra:  INCLUDE "gfx/pokemon/blissey/anim1.asm"
LaprasAnimationExtra:  INCLUDE "gfx/pokemon/lapras/anim1.asm"
SnorlaxAnimationExtra:  INCLUDE "gfx/pokemon/snorlax/anim1.asm"
ChikoritaAnimationExtra:  INCLUDE "gfx/pokemon/chikorita/anim1.asm"
BayleefAnimationExtra:  INCLUDE "gfx/pokemon/bayleef/anim1.asm"

TotodileAnimationExtra:  INCLUDE "gfx/pokemon/totodile/anim1.asm"
CroconawAnimationExtra:  INCLUDE "gfx/pokemon/croconaw/anim1.asm"

StarlyAnimationExtra:  INCLUDE "gfx/pokemon/starly/anim1.asm"
StaraviaAnimationExtra:  INCLUDE "gfx/pokemon/staravia/anim1.asm"
StaraptorAnimationExtra:  INCLUDE "gfx/pokemon/staraptor/anim1.asm"
ShinxAnimationExtra:  INCLUDE "gfx/pokemon/shinx/anim1.asm"
LuxioAnimationExtra:  INCLUDE "gfx/pokemon/luxio/anim1.asm"
LuxrayAnimationExtra:  INCLUDE "gfx/pokemon/luxray/anim1.asm"
CranidosAnimationExtra:  INCLUDE "gfx/pokemon/cranidos/anim1.asm"
RampardosAnimationExtra:  INCLUDE "gfx/pokemon/rampardos/anim1.asm"
ShieldonAnimationExtra:  INCLUDE "gfx/pokemon/shieldon/anim1.asm"
BastiodonAnimationExtra:  INCLUDE "gfx/pokemon/bastiodon/anim1.asm"
DrifloonAnimationExtra:  INCLUDE "gfx/pokemon/drifloon/anim1.asm"
DrifblimAnimationExtra:  INCLUDE "gfx/pokemon/drifblim/anim1.asm"
BronzorAnimationExtra:  INCLUDE "gfx/pokemon/bronzor/anim1.asm"
BronzongAnimationExtra:  INCLUDE "gfx/pokemon/bronzong/anim1.asm"
SpiritombAnimationExtra:  INCLUDE "gfx/pokemon/spiritomb/anim1.asm"
RioluAnimationExtra:  INCLUDE "gfx/pokemon/riolu/anim1.asm"
LucarioAnimationExtra:  INCLUDE "gfx/pokemon/lucario/anim1.asm"
HippopotasAnimationExtra:  INCLUDE "gfx/pokemon/hippopotas/anim1.asm"
HippowdonAnimationExtra:  INCLUDE "gfx/pokemon/hippowdon/anim1.asm"
CroagunkAnimationExtra:  INCLUDE "gfx/pokemon/croagunk/anim1.asm"
ToxicroakAnimationExtra:  INCLUDE "gfx/pokemon/toxicroak/anim1.asm"
SnoverAnimationExtra:  INCLUDE "gfx/pokemon/snover/anim1.asm"
AbomasnowAnimationExtra:  INCLUDE "gfx/pokemon/abomasnow/anim1.asm"
DuskullAnimationExtra:  INCLUDE "gfx/pokemon/duskull/anim1.asm"
DusclopsAnimationExtra:  INCLUDE "gfx/pokemon/dusclops/anim1.asm"
DusknoirAnimationExtra:  INCLUDE "gfx/pokemon/dusknoir/anim1.asm"
SnoruntAnimationExtra:  INCLUDE "gfx/pokemon/snorunt/anim1.asm"
GlalieAnimationExtra:  INCLUDE "gfx/pokemon/glalie/anim1.asm"
FroslassAnimationExtra:  INCLUDE "gfx/pokemon/froslass/anim1.asm"
RotomAnimationExtra:  INCLUDE "gfx/pokemon/rotom/anim1.asm"
BergmiteAnimationExtra:  INCLUDE "gfx/pokemon/bergmite/anim1.asm"
AvaluggAnimationExtra:  INCLUDE "gfx/pokemon/avalugg/anim1.asm"
BasculinAnimationExtra:  INCLUDE "gfx/pokemon/basculin/anim1.asm"
BasculegionAnimationExtra:  INCLUDE "gfx/pokemon/basculegion/anim1.asm"
RuffletAnimationExtra:  INCLUDE "gfx/pokemon/rufflet/anim1.asm"
BraviaryAnimationExtra:  INCLUDE "gfx/pokemon/braviary/anim1.asm"
RaltsAnimationExtra:  INCLUDE "gfx/pokemon/ralts/anim1.asm"
KirliaAnimationExtra:  INCLUDE "gfx/pokemon/kirlia/anim1.asm"
GardevoirAnimationExtra:  INCLUDE "gfx/pokemon/gardevoir/anim1.asm"
GalladeAnimationExtra:  INCLUDE "gfx/pokemon/gallade/anim1.asm"
GoomyAnimationExtra:  INCLUDE "gfx/pokemon/goomy/anim1.asm"
SliggooAnimationExtra:  INCLUDE "gfx/pokemon/sliggoo/anim1.asm"
GoodraAnimationExtra:  INCLUDE "gfx/pokemon/goodra/anim1.asm"
ZoruaAnimationExtra:  INCLUDE "gfx/pokemon/zorua/anim1.asm"
ZoroarkAnimationExtra:  INCLUDE "gfx/pokemon/zoroark/anim1.asm"
GibleAnimationExtra:  INCLUDE "gfx/pokemon/gible/anim1.asm"
GabiteAnimationExtra:  INCLUDE "gfx/pokemon/gabite/anim1.asm"
GarchompAnimationExtra:  INCLUDE "gfx/pokemon/garchomp/anim1.asm"
DratiniAnimationExtra:  INCLUDE "gfx/pokemon/dratini/anim1.asm"
DragonairAnimationExtra:  INCLUDE "gfx/pokemon/dragonair/anim1.asm"
DragoniteAnimationExtra:  INCLUDE "gfx/pokemon/dragonite/anim1.asm"
LarvitarAnimationExtra:  INCLUDE "gfx/pokemon/larvitar/anim1.asm"
PupitarAnimationExtra:  INCLUDE "gfx/pokemon/pupitar/anim1.asm"
TyranitarAnimationExtra:  INCLUDE "gfx/pokemon/tyranitar/anim1.asm"
RaikouAnimationExtra:  INCLUDE "gfx/pokemon/raikou/anim1.asm"
EnteiAnimationExtra:  INCLUDE "gfx/pokemon/entei/anim1.asm"
SuicuneAnimationExtra:  INCLUDE "gfx/pokemon/suicune/anim1.asm"
HeatranAnimationExtra:  INCLUDE "gfx/pokemon/heatran/anim1.asm"
LugiaAnimationExtra:  INCLUDE "gfx/pokemon/lugia/anim1.asm"
Ho_OhAnimationExtra:  INCLUDE "gfx/pokemon/ho_oh/anim1.asm"
CelebiAnimationExtra:  INCLUDE "gfx/pokemon/celebi/anim1.asm"

EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim1.asm"

UnownAAnimationExtra: INCLUDE "gfx/pokemon/unown_a/anim1.asm"
UnownBAnimationExtra: INCLUDE "gfx/pokemon/unown_b/anim1.asm"
UnownCAnimationExtra: INCLUDE "gfx/pokemon/unown_c/anim1.asm"
UnownDAnimationExtra: INCLUDE "gfx/pokemon/unown_d/anim1.asm"
UnownEAnimationExtra: INCLUDE "gfx/pokemon/unown_e/anim1.asm"
UnownFAnimationExtra: INCLUDE "gfx/pokemon/unown_f/anim1.asm"
UnownGAnimationExtra: INCLUDE "gfx/pokemon/unown_g/anim1.asm"
UnownHAnimationExtra: INCLUDE "gfx/pokemon/unown_h/anim1.asm"
UnownIAnimationExtra: INCLUDE "gfx/pokemon/unown_i/anim1.asm"
UnownJAnimationExtra: INCLUDE "gfx/pokemon/unown_j/anim1.asm"
UnownKAnimationExtra: INCLUDE "gfx/pokemon/unown_k/anim1.asm"
UnownLAnimationExtra: INCLUDE "gfx/pokemon/unown_l/anim1.asm"
UnownMAnimationExtra: INCLUDE "gfx/pokemon/unown_m/anim1.asm"
UnownNAnimationExtra: INCLUDE "gfx/pokemon/unown_n/anim1.asm"
UnownOAnimationExtra: INCLUDE "gfx/pokemon/unown_o/anim1.asm"
UnownPAnimationExtra: INCLUDE "gfx/pokemon/unown_p/anim1.asm"
UnownQAnimationExtra: INCLUDE "gfx/pokemon/unown_q/anim1.asm"
UnownRAnimationExtra: INCLUDE "gfx/pokemon/unown_r/anim1.asm"
UnownSAnimationExtra: INCLUDE "gfx/pokemon/unown_s/anim1.asm"
UnownTAnimationExtra: INCLUDE "gfx/pokemon/unown_t/anim1.asm"
UnownUAnimationExtra: INCLUDE "gfx/pokemon/unown_u/anim1.asm"
UnownVAnimationExtra: INCLUDE "gfx/pokemon/unown_v/anim1.asm"
UnownWAnimationExtra: INCLUDE "gfx/pokemon/unown_w/anim1.asm"
UnownXAnimationExtra: INCLUDE "gfx/pokemon/unown_x/anim1.asm"
UnownYAnimationExtra: INCLUDE "gfx/pokemon/unown_y/anim1.asm"
UnownZAnimationExtra: INCLUDE "gfx/pokemon/unown_z/anim1.asm"
UnownExclamationAnimationExtra: INCLUDE "gfx/pokemon/unown_exclamation/anim1.asm"
UnownQuestionAnimationExtra:    INCLUDE "gfx/pokemon/unown_question/anim1.asm"


RaichuAnimationExtra:  INCLUDE "gfx/pokemon/raichu/anim1.asm"
Raichu_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/raichu_alolan/anim1.asm"

VulpixAnimationExtra:  INCLUDE "gfx/pokemon/vulpix/anim1.asm"
Vulpix_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/vulpix_alolan/anim1.asm"

NinetalesAnimationExtra:  INCLUDE "gfx/pokemon/ninetales/anim1.asm"
Ninetales_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/ninetales_alolan/anim1.asm"

GeodudeAnimationExtra:  INCLUDE "gfx/pokemon/geodude/anim1.asm"
Geodude_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/geodude_alolan/anim1.asm"

GravelerAnimationExtra:  INCLUDE "gfx/pokemon/graveler/anim1.asm"
Graveler_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/graveler_alolan/anim1.asm"

GolemAnimationExtra:  INCLUDE "gfx/pokemon/golem/anim1.asm"
Golem_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/golem_alolan/anim1.asm"

GrimerAnimationExtra:  INCLUDE "gfx/pokemon/grimer/anim1.asm"
Grimer_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/grimer_alolan/anim1.asm"

MukAnimationExtra:  INCLUDE "gfx/pokemon/muk/anim1.asm"
Muk_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/muk_alolan/anim1.asm"

ExeggutorAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor/anim1.asm"
Exeggutor_AlolanAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor_alolan/anim1.asm"


PonytaAnimationExtra:  INCLUDE "gfx/pokemon/ponyta/anim1.asm"
Ponyta_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/ponyta_galarian/anim1.asm"

RapidashAnimationExtra:  INCLUDE "gfx/pokemon/rapidash/anim1.asm"
Rapidash_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/rapidash_galarian/anim1.asm"

SlowpokeAnimationExtra:  INCLUDE "gfx/pokemon/slowpoke/anim1.asm"
Slowpoke_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/slowpoke_galarian/anim1.asm"

SlowbroAnimationExtra:  INCLUDE "gfx/pokemon/slowbro/anim1.asm"
Slowbro_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/slowbro_galarian/anim1.asm"

SlowkingAnimationExtra:  INCLUDE "gfx/pokemon/slowking/anim1.asm"
Slowking_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/slowking_galarian/anim1.asm"

WeezingAnimationExtra:  INCLUDE "gfx/pokemon/weezing/anim1.asm"
Weezing_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/weezing_galarian/anim1.asm"

CorsolaAnimationExtra:  INCLUDE "gfx/pokemon/corsola/anim1.asm"
Corsola_GalarianAnimationExtra:  INCLUDE "gfx/pokemon/corsola_galarian/anim1.asm"


GrowlitheAnimationExtra:  INCLUDE "gfx/pokemon/growlithe/anim1.asm"
Growlithe_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/growlithe_hisuian/anim1.asm"

ArcanineAnimationExtra:  INCLUDE "gfx/pokemon/arcanine/anim1.asm"
Arcanine_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/arcanine_hisuian/anim1.asm"

VoltorbAnimationExtra:  INCLUDE "gfx/pokemon/voltorb/anim1.asm"
Voltorb_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/voltorb_hisuian/anim1.asm"

ElectrodeAnimationExtra:  INCLUDE "gfx/pokemon/electrode/anim1.asm"
Electrode_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/electrode_hisuian/anim1.asm"

TyphlosionAnimationExtra:  INCLUDE "gfx/pokemon/typhlosion/anim1.asm"
Typhlosion_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/typhlosion_hisuian/anim1.asm"

QwilfishAnimationExtra:  INCLUDE "gfx/pokemon/qwilfish/anim1.asm"
Qwilfish_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/qwilfish_hisuian/anim1.asm"

SneaselAnimationExtra:  INCLUDE "gfx/pokemon/sneasel/anim1.asm"
Sneasel_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/sneasel_hisuian/anim1.asm"

SamurottAnimationExtra:  INCLUDE "gfx/pokemon/samurott/anim1.asm"
Samurott_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/samurott_hisuian/anim1.asm"

DecidueyeAnimationExtra:  INCLUDE "gfx/pokemon/decidueye/anim1.asm"
Decidueye_HisuianAnimationExtra:  INCLUDE "gfx/pokemon/decidueye_hisuian/anim1.asm"


NoctowlAnimationExtra:  INCLUDE "gfx/pokemon/noctowl/anim1.asm"
Noctowl_ImmortalAnimationExtra:  INCLUDE "gfx/pokemon/noctowl_immortal/anim1.asm"

UrsalunaAnimationExtra:  INCLUDE "gfx/pokemon/ursaluna/anim1.asm"
Ursaluna_BloodmoonAnimationExtra:  INCLUDE "gfx/pokemon/ursaluna_bloodmoon/anim1.asm"

FeraligatrAnimationExtra:  INCLUDE "gfx/pokemon/feraligatr/anim1.asm"
Feraligatr_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/feraligatr_ancestor/anim1.asm"

MeganiumAnimationExtra:  INCLUDE "gfx/pokemon/meganium/anim1.asm"
Meganium_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/meganium_ancestor/anim1.asm"

MagcargoAnimationExtra:  INCLUDE "gfx/pokemon/magcargo/anim1.asm"
Magcargo_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/magcargo_ancestor/anim1.asm"

XatuAnimationExtra:  INCLUDE "gfx/pokemon/xatu/anim1.asm"
Xatu_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/xatu_ancestor/anim1.asm"

LedianAnimationExtra:  INCLUDE "gfx/pokemon/ledian/anim1.asm"
Ledian_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/ledian_ancestor/anim1.asm"

AlakazamAnimationExtra:  INCLUDE "gfx/pokemon/alakazam/anim1.asm"
Alakazam_AncestorAnimationExtra:  INCLUDE "gfx/pokemon/alakazam_ancestor/anim1.asm"

