FramesPointers:
	table_width 2, FramesPointers
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw OshawottFrames
	dw DewottFrames
	dw SamurottFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw SentretFrames
	dw FurretFrames
	dw PikachuFrames
	dw RaichuFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw TogeticFrames
	dw TogekissFrames
	dw DunsparceFrames
	dw DudunsparceFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw WooperFrames
	dw QuagsireFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw UnownFrames
	dw OnixFrames
	dw SteelixFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw ParasFrames
	dw ParasectFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw PolitoedFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw BellossomFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw PinecoFrames
	dw ForretressFrames
	dw NidoranFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw SunfloraFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw SudowoodoFrames
	dw ScytherFrames
	dw ScizorFrames
	dw KleavorFrames
	dw PinsirFrames
	dw MinsirFrames
	dw HeracrossFrames
	dw KoffingFrames
	dw WeezingFrames
	dw GrimerFrames
	dw MukFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw AipomFrames
	dw AmbipomFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw StantlerFrames
	dw WyrdeerFrames
	dw MarillFrames
	dw AzumarillFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw AnnihilapeFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw HitmontopFrames
	dw GirafarigFrames
	dw FarigirafFrames
	dw TaurosFrames
	dw MiltankFrames
	dw MagmarFrames
	dw MagmortarFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw ElectivireFrames
	dw NatuFrames
	dw XatuFrames
	dw QwilfishFrames
	dw OverqwilFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw ShuckleFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw SeadraFrames
	dw KingdraFrames
	dw GligarFrames
	dw GliscorFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw UrsalunaFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw PonytaFrames
	dw RapidashFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw MurkrowFrames
	dw HonchkrowFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SneaselFrames
	dw WeavileFrames
	dw SneaslerFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw Porygon_zFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw LaprasFrames
	dw SnorlaxFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw GrotleFrames
	dw TorterraFrames
	dw MonfernoFrames
	dw InfernapeFrames
	dw PrinplupFrames
	dw EmpoleonFrames
	dw StaraviaFrames
	dw StaraptorFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw CranidosFrames
	dw RampardosFrames
	dw ShieldonFrames
	dw BastiodonFrames
	dw VespiquenFrames
	dw DrifloonFrames
	dw DrifblimFrames
	dw BronzorFrames
	dw BronzongFrames
	dw SpiritombFrames
	dw LucarioFrames
	dw HippopotasFrames
	dw HippowdonFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw DuskullFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw FroslassFrames
	dw RotomFrames
	dw BergmiteFrames
	dw AvaluggFrames
	dw BasculegionFrames
	dw BraviaryFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw GoomyFrames
	dw SliggooFrames
	dw GoodraFrames
	dw ZoruaFrames
	dw ZoroarkFrames
	dw GibleFrames
	dw GabiteFrames
	dw GarchompFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw HeatranFrames
	dw LugiaFrames
	dw Ho_ohFrames
	dw CelebiFrames

	assert_table_length NUM_POKEMON

	dw EggFrames

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames

	dw Raichu_alolanFrames
	dw Vulpix_alolanFrames
	dw Ninetales_alolanFrames
	dw Geodude_alolanFrames
	dw Graveler_alolanFrames
	dw Golem_alolanFrames
	dw Grimer_alolanFrames
	dw Muk_alolanFrames
	dw Exeggutor_alolanFrames


	dw Ponyta_galarianFrames
	dw Rapidash_galarianFrames
	dw Slowpoke_galarianFrames
	dw Slowbro_galarianFrames
	dw Slowking_galarianFrames
	dw Weezing_galarianFrames
	dw Corsola_galarianFrames


	dw Growlithe_hisuianFrames
	dw Arcanine_hisuianFrames
	dw Voltorb_hisuianFrames
	dw Electrode_hisuianFrames
	dw Typhlosion_hisuianFrames
	dw Qwilfish_hisuianFrames
	dw Sneasel_hisuianFrames
	dw Samurott_hisuianFrames
	dw Decidueye_hisuianFrames


	dw Noctowl_immortalFrames
	dw Ursaluna_bloodmoonFrames

	dw Feraligatr_ancestorFrames
	dw Meganium_ancestorFrames
	dw Magcargo_ancestorFrames
	dw Xatu_ancestorFrames

	assert_table_length NUM_UNIQUE_POKEMON
